### ISSUE TITLE
Query Patterns: Followup Fixes

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentytwo#90]
Following up from #84, there are a few query patterns that require followup: 

## Default Posts

- There's no current way to enforce a responsive square shape for featured images. (https://github.com/WordPress/gutenberg/issues/35524) _Edit: Not coming for 5.9._ 

## Simple Blog Posts

- [x] The margin set on the post titles does not appear correct on the front-end. (https://github.com/WordPress/gutenberg/issues/35522)

## Image grid posts

- [x] Post date is supposed to be stacked. This would be solved by the addition of a flex-wrap option. (https://github.com/WordPress/gutenberg/issues/35525)
- [x] Post date can not be formatted into the "11.11.2021" format as originally designed. (https://github.com/WordPress/gutenberg/issues/34762)

## Large post titles

- [x] Post date can not be formatted into the "Nov 11" format as originally designed. (https://github.com/WordPress/gutenberg/issues/34762)

## Irregular posts grid

- [ ] Since this requires use of multiple query blocks, it cannot include post pagination.

**Comment by carolinan** [comment]
For the post dates, this pull request could use more reviews https://github.com/WordPress/gutenberg/pull/35864

**Comment by carolinan** [comment]
@kjellr I really like the irregular posts design. I think it can be kept without pagination. If that's not an option, it can't be done without one query and custom CSS.

On the front the sticky posts are repeated in every column. 
Pattern added to a **post**, front view:
![image](https://user-images.githubusercontent.com/7422055/140073305-6877b348-a435-43b9-b559-5120422efff2.png)

here I replaced the query on **index** with the pattern:
![image](https://user-images.githubusercontent.com/7422055/140074400-a4ff7848-b506-498a-ab5b-4ce3875d0821.png)

I messed up the width here. Chances are other users will do the same. Not sure how users can be guided.

Gutenberg issue for sticky posts: https://github.com/WordPress/gutenberg/issues/35322#issuecomment-946574994

**Comment by kjellr** [comment]
>  There's no current way to enforce a responsive square shape for featured images. ([Post Featured Image]: Allow cropping and/or constraining to a certain ratio gutenberg#35524)

This one doesn't look likely for 5.9 since it would be a new feature and it's past the feature freeze. Going to cross it out for now. 

> Since this requires use of multiple query blocks, it cannot include post pagination.

I'm a little torn on this one. I think the two options are: 

- Do nothing.
- Trim down the number of posts so that this acts more as a "featured posts" layout and less like a page of posts. 

Any thoughts/preferences?

**Comment by kjellr** [comment]
I'm going to close this one and just leave that last pattern as is for the time being. We can always re-adjust if we get more design tools down the line. 👍
